p8105_hw2_sc5351
================
Shaoyu Chen
2023-10-02

## Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(dplyr)
```

Clean the data in pols-month.csv.

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
) 
pols =
  read_csv("./data/fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |> 
  left_join(x = _, y = month_df) |>
  select(year, month, everything(), -day, -starts_with("prez"))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_num)`

Clean the data in snp.csv

``` r
snp = 
  read_csv("./data/fivethirtyeight_datasets/snp.csv") |>
  separate(date, into = c("month", "day", "year"), convert = TRUE) |>
  arrange(year, month) |>
  mutate(month = month.name[month]) |>
  select(year, month, close) 
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

tidy the unemployment data

``` r
unemployment = 
  read_csv("./data/fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec,
    names_to = "month_abb",
    values_to = "unemployment"
  ) |>
  left_join(x =_, y = month_df) |>
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abb)`

Join the datasets by merging snp into pols, and merging unemployment
into the result.

``` r
data = 
  left_join(pols, snp) |>
  left_join(x = _, y = unemployment)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
str(data)
```

    ## tibble [822 × 13] (S3: tbl_df/tbl/data.frame)
    ##  $ year        : num [1:822] 1947 1947 1947 1947 1947 ...
    ##  $ month       : chr [1:822] "January" "February" "March" "April" ...
    ##  $ month_num   : int [1:822] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ gov_gop     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : num [1:822] 51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : num [1:822] 253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : num [1:822] 45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : num [1:822] 198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president   : chr [1:822] "dem" "dem" "dem" "dem" ...
    ##  $ month_abb   : chr [1:822] "Jan" "Feb" "Mar" "Apr" ...
    ##  $ close       : num [1:822] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num [1:822] NA NA NA NA NA NA NA NA NA NA ...

## Problem 2

read and clean trash wheel data

``` r
mr_trash_wheel = 
  read_excel(
    "./data/202309 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N586",
    skip = 1) |>
  janitor::clean_names() |>
  separate(date, into = c("year", "month", "day"), convert = TRUE) |>
  mutate(
  homes_powered = (weight_tons * (500/30)),
  month = month.name[as.numeric(month)],
  trash_wheel_name = "Mr. Trash Wheel"
  )
mr_trash_wheel
```

    ## # A tibble: 584 × 15
    ##    dumpster  year month   day weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <int> <chr> <int>       <dbl>              <dbl>           <dbl>
    ##  1        1  2014 May      16        4.31                 18            1450
    ##  2        2  2014 May      16        2.74                 13            1120
    ##  3        3  2014 May      16        3.45                 15            2450
    ##  4        4  2014 May      17        3.1                  15            2380
    ##  5        5  2014 May      17        4.06                 18             980
    ##  6        6  2014 May      20        2.71                 13            1430
    ##  7        7  2014 May      21        1.91                  8             910
    ##  8        8  2014 May      28        3.7                  16            3580
    ##  9        9  2014 June      5        2.52                 14            2400
    ## 10       10  2014 June     11        3.76                 18            1340
    ## # ℹ 574 more rows
    ## # ℹ 8 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   sports_balls <dbl>, homes_powered <dbl>, trash_wheel_name <chr>

Read and clean professor trash wheel

``` r
prof_trash_wheel = 
  read_excel(
    "./data/202309 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M108",
    skip = 1) |>
  janitor::clean_names() |>
  separate(date, into = c("year", "month", "day"), convert = TRUE) |>
  mutate(
  homes_powered = (weight_tons * (500/30)),
  month = month.name[as.numeric(month)],
  prof_wheel_name = "Professor Trash Wheel"
  )
prof_trash_wheel
```

    ## # A tibble: 106 × 14
    ##    dumpster  year month      day weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <int> <chr>    <int>       <dbl>              <dbl>           <dbl>
    ##  1        1  2017 January      2        1.79                 15            1950
    ##  2        2  2017 January     30        1.58                 15            9540
    ##  3        3  2017 February    26        2.32                 18            8350
    ##  4        4  2017 February    26        3.72                 15            8590
    ##  5        5  2017 February    28        1.45                 15            7830
    ##  6        6  2017 March       30        1.71                 15            8210
    ##  7        7  2017 April        1        1.82                 15            9830
    ##  8        8  2017 April       20        2.37                 15            9240
    ##  9        9  2017 May         10        2.64                 15            9540
    ## 10       10  2017 May         26        2.78                 15            8230
    ## # ℹ 96 more rows
    ## # ℹ 7 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, prof_wheel_name <chr>

read and clean Gwynnda trash wheel

``` r
gwyn_trash_wheel = 
  read_excel(
    "./data/202309 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda Trash Wheel",
    range = "A2:L157",
    skip = 1) |>
  janitor::clean_names() |>
  separate(date, into = c("year", "month", "day"), convert = TRUE) |>
  mutate(
  homes_powered = (weight_tons * (500/30)),
  month = month.name[as.numeric(month)],
  gwyn_wheel_name = "Gwynnda Trash Wheel"
  )
gwyn_trash_wheel
```

    ## # A tibble: 155 × 13
    ##    dumpster  year month    day weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <int> <chr>  <int>       <dbl>              <dbl>           <dbl>
    ##  1        1  2021 July       3        0.93                 15            1200
    ##  2        2  2021 July       7        2.26                 15            2000
    ##  3        3  2021 July       7        1.62                 15            1800
    ##  4        4  2021 July      16        1.76                 15            1000
    ##  5        5  2021 July      30        1.53                 15            2100
    ##  6        6  2021 August    11        2.06                 15            2400
    ##  7        7  2021 August    14        1.9                  15            2700
    ##  8        8  2021 August    16        2.16                 15            3000
    ##  9        9  2021 August    16        2.6                  15             980
    ## 10       10  2021 August    17        3.21                 15             240
    ## # ℹ 145 more rows
    ## # ℹ 6 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, homes_powered <dbl>,
    ## #   gwyn_wheel_name <chr>

Combining three datasets

``` r
trash_wheel_tidy = bind_rows(mr_trash_wheel, prof_trash_wheel, gwyn_trash_wheel)
trash_wheel_tidy
```

    ## # A tibble: 845 × 17
    ##    dumpster  year month   day weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <int> <chr> <int>       <dbl>              <dbl>           <dbl>
    ##  1        1  2014 May      16        4.31                 18            1450
    ##  2        2  2014 May      16        2.74                 13            1120
    ##  3        3  2014 May      16        3.45                 15            2450
    ##  4        4  2014 May      17        3.1                  15            2380
    ##  5        5  2014 May      17        4.06                 18             980
    ##  6        6  2014 May      20        2.71                 13            1430
    ##  7        7  2014 May      21        1.91                  8             910
    ##  8        8  2014 May      28        3.7                  16            3580
    ##  9        9  2014 June      5        2.52                 14            2400
    ## 10       10  2014 June     11        3.76                 18            1340
    ## # ℹ 835 more rows
    ## # ℹ 10 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   sports_balls <dbl>, homes_powered <dbl>, trash_wheel_name <chr>,
    ## #   prof_wheel_name <chr>, gwyn_wheel_name <chr>

The final tidy dataset contains with 3 trash wheels and has totally 845
rows and 17 columns.

Key variables are `dumpster`, `year`, `month`, `day`, `weight_tons`,
`homes_powered`.

The total weight of trash collected by Professor Trash Wheel is 216.26
tons.

The total number of cigarette butts collected by Gwynnda in July of 2021
is 16300.

\##Problem 3

import,clean and tidy the baseline.

``` r
mci_baseline = 
  read_csv("./data/data_mci/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |>
  mutate(
    sex = recode(sex, "1" = "Male", "0" = "Female"),
    apoe4 = recode(apoe4, "1" = "carrier", "0" = "no carrier")
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline_remove = filter(mci_baseline, age_at_onset != "." )
```

Important steps in the import process are to convert `sex` and `apoe4`
into non numerical values, and remove any participants who do not meet
`age_at_onest`.

483 were recruited at baseline.

97 participants developed MCI.

The average baseline age is 65.0467909.

The proporton of women in the study are APOE4 carriers is 30%.
