---
title: "p8105_hw2_sc5351"
author: "Shaoyu Chen"
output: github_document
date: "2023-10-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1
```{r}
library(tidyverse)
library(readxl)
```
Clean the data in pols-month.csv.
```{r}

month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
) 
pols =
  read_csv("./data/fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |> 
  left_join(x = _, y = month_df) |>
  select(year, month, everything(), -day, -starts_with("prez"))

```
Clean the data in snp.csv
```{r}
snp = 
  read_csv("./data/fivethirtyeight_datasets/snp.csv") |>
  separate(date, into = c("month", "day", "year"), convert = TRUE) |>
  arrange(year, month) |>
  mutate(month = month.name[month]) |>
  select(year, month, close) 

```
tidy the unemployment data 
```{r}
unemployment = 
  read_csv("./data/fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec,
    names_to = "month_abb",
    values_to = "unemployment"
  ) |>
  left_join(x =_, y = month_df) |>
  select(year, month, unemployment)


```
Join the datasets by merging snp into pols, and merging unemployment into the result.
```{r}
data = 
  left_join(pols, snp) |>
  left_join(x = _, y = unemployment)
str(data)
```



## Problem 2
read and clean trash wheel data
```{r read and clean trash wheel data}
mr_trash_wheel = 
  read_excel(
    "./data/202309 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N586",
    skip = 1) |>
  janitor::clean_names() |>
  separate(date, into = c("year", "month", "day"), convert = TRUE) |>
  mutate(
  homes_powered = (weight_tons * (500/30)),
  month = month.name[as.numeric(month)],
  trash_wheel_name = "Mr. Trash Wheel"
  )
mr_trash_wheel
```

Read and clean professor trash wheel
```{r}
prof_trash_wheel = 
  read_excel(
    "./data/202309 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M108",
    skip = 1) |>
  janitor::clean_names() |>
  separate(date, into = c("year", "month", "day"), convert = TRUE) |>
  mutate(
  homes_powered = (weight_tons * (500/30)),
  month = month.name[as.numeric(month)],
  prof_wheel_name = "Professor Trash Wheel"
  )
prof_trash_wheel
```


